//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCApp.Tests.HelloWorldService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWorldService.IHelloWorldService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IHelloWorldService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/GetTodaysData", ReplyAction="http://tempuri.org/IHelloWorldService/GetTodaysDataResponse")]
        WebMVCApp.HelloWorldService.TodaysDataResponse GetTodaysData(WebMVCApp.HelloWorldService.TodaysDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloWorldService/GetTodaysData", ReplyAction="http://tempuri.org/IHelloWorldService/GetTodaysDataResponse")]
        System.Threading.Tasks.Task<WebMVCApp.HelloWorldService.TodaysDataResponse> GetTodaysDataAsync(WebMVCApp.HelloWorldService.TodaysDataRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloWorldServiceChannel : WebMVCApp.Tests.HelloWorldService.IHelloWorldService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldServiceClient : System.ServiceModel.ClientBase<WebMVCApp.Tests.HelloWorldService.IHelloWorldService>, WebMVCApp.Tests.HelloWorldService.IHelloWorldService {
        
        public HelloWorldServiceClient() {
        }
        
        public HelloWorldServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebMVCApp.HelloWorldService.TodaysDataResponse GetTodaysData(WebMVCApp.HelloWorldService.TodaysDataRequest request) {
            return base.Channel.GetTodaysData(request);
        }
        
        public System.Threading.Tasks.Task<WebMVCApp.HelloWorldService.TodaysDataResponse> GetTodaysDataAsync(WebMVCApp.HelloWorldService.TodaysDataRequest request) {
            return base.Channel.GetTodaysDataAsync(request);
        }
    }
}
